<?php
print'
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-4 mb-0 text-body-secondary">&copy; 2024 Zafer Bayraktarov,<br>FMI Plovdiv</p>

      <a href="/"
        class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img src="img\Gym logo.png" alt="Logo" width="75" height="75">
      </a>

      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body">About</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body">Exercises</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body">Contact</a></li>
      </ul>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/js/scripts.js"></script>
</body>

</html>
';




?>